name: Alexander Volkmann
markdown: kramdown
mathjax: true
plugins: ['jekyll/scholar']
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
permalink: /blog/:year/:month/:day/:title
